main: com.cavetale.caves.CavesPlugin
name: Caves
version: 0.1
api-version: 1.13
description: Generate more interesting themed caves
author: StarTux
website: https://cavetale.com
depend: []
softdepend: [Decorator]
commands:
  caves:
    aliases: [cave]
    permission: caves.caves
    usage: |-
      /caves test - Test
